### ISSUE TITLE
[BUG] CircleCI broken

### ISSUE THREAD

**Issue by Cheva14** [Group-4W/Sprint4#17]
**Describe the bug**
CircleCI not working at all, it used to work before but now that we use a different directory, it doesn't work

**To Reproduce**
1. Just commit any changes
2. CircleCI will fail

**Expected behavior**
CircleCI should pass.

**Screenshots**

**Desktop (please complete the following information):**
 - Device: macbookairm1
 - OS: macoslatelst
 - Browser chrome

**Additional context**

**Comment by PyEddy** [comment]
Fixed, had to adjust the working directory and path
